//
//  Key.h
//  DFWeChatView
//
//  Created by Allen Zhong on 15/4/22.
//  Copyright (c) 2015年 Datafans, Inc. All rights reserved.
//

#ifndef DFWeChatView_Key_h
#define DFWeChatView_Key_h



#define NOTIFY_EMOTION_EMOJI @"NOTIFY_EMOTION_EMOJI"
#define NOTIFY_EMOTION_EMOJI_SEND @"NOTIFY_EMOTION_EMOJI_SEND"

#define NOTIFY_TEXTVIEW_CONTENT_CHANGE @"NOTIFY_TEXTVIEW_CONTENT_CHANGE"


#define NOTIFY_TEXT_MESSAGE @"NOTIFY_TEXT_MESSAGE"
#define NOTIFY_EMOTION_MESSAGE @"NOTIFY_EMOTION_MESSAGE"
#define NOTIFY_IMAGE_MESSAGE @"NOTIFY_IMAGE_MESSAGE"
#define NOTIFY_VOICE_MESSAGE @"NOTIFY_VOICE_MESSAGE"



#define NOTIFY_IMAGE_CLIECKED @"NOTIFY_IMAGE_CLIECKED"

#endif
